{
    "url": "https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/1.26.0/snowpark/api/snowflake.snowpark.exceptions.SnowparkInvalidObjectNameException",
    "title": "snowflake.snowpark.exceptions.SnowparkInvalidObjectNameException | Snowflake Documentation",
    "paragraphs": [
        "Bases: SnowparkGeneralException",
        "Exception for inputting an invalid object name. Checked locally.",
        "This exception is specifically raised for error codes: 1500.",
        "Was this page helpful?"
    ]
}